from django.conf.urls import patterns, url
from smapp import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^login/$', views.login_user, name='login'),
                       url(r'^login_concierge/$', views.login_concierge, name='login_concierge'),
                       url(r'^logout/$', views.user_logout, name='logout'),
                       url(r'^dashboard/$', views.dashboard, name='dashboard'),
                       url(r'^dashboard_concierge/$', views.dashboard_concierge, name='dashboard_concierge'),
                       url(r'^register_visit/$', views.register_visit, name='register visit'),
                       url(r'^historical_record/$', views.historical_record, name='historical record'),
                       url(r'^visit_record/$', views.visit_record, name='visit record'),
                       url(r'^publish/$', views.publish, name='publish'),
                       url(r'^publications_wall/$', views.publications_wall, name='publications_wall'),
                       url(r'^calendar_locations/$', views.calendar, name='calendar'),
                       url(r'^all_events/$', views.all_events, name='calendar'),
                       url(r'^create_event/$', views.create_event, name='create_event'),
                       url(r'^publications_wall_consierge/$', views.publications_wall_consierge, name='publications_wall_consierge'),
                       url(r'^calendar_consierge/$', views.calendar_consierge, name='calendar_consierge'),
                       url(r'^login_owner/$', views.login_owner, name='login_owner'),
                       url(r'^dashboard_owner/$', views.dashboard_owner, name='dashboard_owner'),
                       url(r'^register_rent/$', views.register_rent, name='register_rent'),
                       url(r'^historical_record_owner/$', views.historical_record_owner, name='historical_record_owner'),
                       url(r'^publications_wall_owner/$', views.publications_wall_owner, name='publications_wall_owner'),
                       url(r'^calendar_owner/$', views.calendar_owner, name='calendar_owner'),
                       url(r'^pay_list/$', views.rent_pay, name='rent_pay'),
                       )