# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-04 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='residentOrigin',
        ),
        migrations.RemoveField(
            model_name='building',
            name='owner',
        ),
        migrations.AddField(
            model_name='usersm',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smapp.Apartment'),
        ),
        migrations.AddField(
            model_name='usersm',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smapp.Building'),
        ),
        migrations.DeleteModel(
            name='Resident',
        ),
    ]
