# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-04 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0002_auto_20161104_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='received',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
