# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smapp', '0003_auto_20161104_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consierge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smapp.Building')),
                ('userOrigin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('userOrigin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smapp.Apartment')),
                ('userOrigin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersm',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='usersm',
            name='building',
        ),
        migrations.RemoveField(
            model_name='usersm',
            name='userOrigin',
        ),
        migrations.AlterField(
            model_name='visit',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smapp.Resident'),
        ),
        migrations.DeleteModel(
            name='UserSM',
        ),
        migrations.AddField(
            model_name='building',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='smapp.Owner'),
            preserve_default=False,
        ),
    ]
