# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 21:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0004_auto_20161114_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('hour', models.TimeField(default=datetime.datetime.now)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='consierge',
            name='rut',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='owner',
            name='rut',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='resident',
            name='rut',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='visit',
            name='rut',
            field=models.CharField(max_length=12),
        ),
        migrations.AddField(
            model_name='publication',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smapp.Resident'),
        ),
    ]
