# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0005_auto_20161114_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
