# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-19 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0009_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
