# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-19 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0010_auto_20161119_1438'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
