# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-27 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0012_auto_20161122_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smapp.Resident')),
            ],
        ),
    ]
