# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-27 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0013_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='amount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
