# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-28 00:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0014_rent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 28, 0, 15, 48, 423924)),
        ),
    ]
